name: real_only
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  group_radio_button: ^1.3.0
  http: ^1.1.0
  intl: ^0.18.1
  kakao_flutter_sdk_user: ^1.4.1
  kakao_map_plugin: ^0.1.6
  kpostal: ^0.5.1
  open_share_plus: ^1.2.0
  path_provider: ^2.1.0
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
  fullscreen: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/NotoSansKR/NotoSansKR-Black.otf
          weight: 900

  assets:
    - assets/
