import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFFFF951A),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDCC1),
  onPrimaryContainer: Color(0xFF2E1500),
  secondary: Color(0xFF8A5100),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFDCBD),
  onSecondaryContainer: Color(0xFF2C1600),
  tertiary: Color(0xFF5A6238),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFDFE8B2),
  onTertiaryContainer: Color(0xFF181E00),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFFFF),
  onBackground: Color(0xFF201B17),
  surface: Color(0xFFFFFFFF),
  onSurface: Color(0xFF201B17),
  surfaceVariant: Color(0xFFF2DFD1),
  onSurfaceVariant: Color(0xFF51443A),
  outline: Color(0xFFE8E8E8),
  onInverseSurface: Color(0xFFFAEFE8),
  inverseSurface: Color(0xFF352F2B),
  inversePrimary: Color(0xFFFFB877),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFFF951A),
  outlineVariant: Color(0xFFD6C3B6),
  scrim: Color(0xFF000000),
);
